// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr36RzzqAUzHn1hIDs_ivBa36X8Sm-tME',
    appId: '1:945802134556:web:7ac7b9abde73bd1b89cbd9',
    messagingSenderId: '945802134556',
    projectId: 'first-project-d4e40',
    authDomain: 'first-project-d4e40.firebaseapp.com',
    storageBucket: 'first-project-d4e40.appspot.com',
    measurementId: 'G-TZTGEJQL32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6vVQTCiPgRKM8qMd8M0oy1JLkbs3Vfn0',
    appId: '1:945802134556:android:4a7e29c5bbaeaf2c89cbd9',
    messagingSenderId: '945802134556',
    projectId: 'first-project-d4e40',
    storageBucket: 'first-project-d4e40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Olv21wQubMp4xoU5-skd0dMWMzqEVTo',
    appId: '1:945802134556:ios:4161fd8acab9656a89cbd9',
    messagingSenderId: '945802134556',
    projectId: 'first-project-d4e40',
    storageBucket: 'first-project-d4e40.appspot.com',
    iosBundleId: 'com.example.flutterTask2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Olv21wQubMp4xoU5-skd0dMWMzqEVTo',
    appId: '1:945802134556:ios:4161fd8acab9656a89cbd9',
    messagingSenderId: '945802134556',
    projectId: 'first-project-d4e40',
    storageBucket: 'first-project-d4e40.appspot.com',
    iosBundleId: 'com.example.flutterTask2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr36RzzqAUzHn1hIDs_ivBa36X8Sm-tME',
    appId: '1:945802134556:web:250688311429529489cbd9',
    messagingSenderId: '945802134556',
    projectId: 'first-project-d4e40',
    authDomain: 'first-project-d4e40.firebaseapp.com',
    storageBucket: 'first-project-d4e40.appspot.com',
    measurementId: 'G-91KZFKMVX5',
  );
}
